<?php

/**
* Implements hook_menu().
*/
function fp_ui_menu() {
  $items = array();
  $items['ftp_put'] = array(
    'title' => 'Process FTP.',
    'description' => 'Initiate an FTP transfer.',
    'page callback' => 'ftp_put_nomprocess',
    'access callback'  => 'user_access',
    'access arguments' => array('process FTP requests over a URL'),	
    'type' => MENU_CALLBACK
  );
  $items['admin/config/services/ftp_put'] = array(
    'title' => 'FTP Put module settings',
    'description' => 'Description of the FTP Put settings page',
    'page callback' => 'drupal_get_form',
    'access callback'  => 'user_access',
    'page arguments' => array('fp_ui_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

 /**
* Implements hook_permission().
*/
function fp_ui_permission() {
  return array(
    'process FTP requests over a URL' =>  array(
      'title' => t('FTP Put requests'),
      'description' => t('process FTP requests over a URL, /ftp_put.'),
    ),
	);
}

/**
* Form generator for module settings.
*/
function fp_ui_form($form, &$form_state) {
  $form['fp_ui_outputdir'] = array(
    '#type' => 'textfield',
    '#title' => t('local output dir'),
    '#default_value' => variable_get('fp_ui_outputdir', '/home/filexfer/output'),
    '#size' => 80,
    '#maxlength' => 80,
    '#description' => t("Directory to store submitted encrypted application files on the local server."),
    '#required' => TRUE,
  );
  $form['fp_ui_archivedir'] = array(
    '#type' => 'textfield',
    '#title' => t('local archive dir'),
    '#default_value' => variable_get('fp_ui_archivedir', '/home/filexfer/archive'),
    '#size' => 80,
    '#maxlength' => 80,
    '#description' => t("Directory to archive submitted encrypted application files on the local server."),
    '#required' => TRUE,
  );
  $form['fp_ui_tempdir'] = array(
    '#type' => 'textfield',
    '#title' => t('local temp dir'),
    '#default_value' => variable_get('fp_ui_tempdir', 'sites/default/files'),
    '#size' => 80,
    '#maxlength' => 80,
    '#description' => t("Directory to store temp files on the local server."),
    '#required' => TRUE,
  );
  $form['fp_ui_log'] = array(
    '#type' => 'checkbox',
    '#title' => t('Keep log'),
    '#default_value' => variable_get('fp_ui_log', 0),
    '#description' => t("Keep a log of all FTP transaction"),
    '#required' => FALSE,
  );
  $form = system_settings_form($form);
  return $form;
}


/**
* Implements hook_views_api().
 */
function fp_ui_views_api() {
 return array(
   'api' => 3,
   'path' => drupal_get_path('module', 'fp_ui'),
 );
}
// ***************************  Hooks end  ***************************
//                  **********************************
